baseURL = "https://sc2.outright.io/"
languageCode = "en-us"
title = "StarCraft II Maps by Outright Mental"
description = "We love playing StarCraft II, and wanted to try out some map ideas of our own."